---
- apt: pkg=python-mysqldb state=latest
- stat: path=/etc/apt/sources.list.d/dotinfra_evqueue.list
  register: evqueuerepo
- get_url: validate_certs=no url=https://packagecloud.io/install/repositories/evqueue/core/script.deb.sh dest=/tmp/packagecloud_install.sh
  when: not evqueuerepo.stat.exists
- command: /bin/bash /tmp/packagecloud_install.sh
  when: not evqueuerepo.stat.exists
- apt: pkg=evqueue-core state=latest

- apt: pkg=mysql-server state=latest
- mysql_db: name=evqueue state=present
- copy: src=create_tables.sql dest=/tmp
- mysql_db: name=evqueue state=import target=/tmp/create_tables.sql

- name: evqueue core configuration file update
  template: src=evqueue.conf.j2
    dest=/etc/evqueue.conf
    backup=yes
    owner=0 group=0 mode=0644
  notify:
  - restart evqueue
