---
- apt: pkg=git state=latest
- apt: pkg=curl state=latest
- apt: pkg=php5-fpm state=latest
- apt: pkg=php5-mysql state=latest
- apt: pkg=php5-curl state=latest
- apt: pkg=php5-xsl state=latest
- apt: pkg=mysql-client state=latest
- apt: pkg=apache2-mpm-worker state=latest
- apache2_module: state=present name=proxy_fcgi

- git: repo=https://github.com/coldsource/evqueue-frontend-php.git dest=/var/www/html/evqueue
- file: path=/var/log/evqueue state=directory mode=0755 owner=www-data group=www-data
- file: path=/var/log/evqueue/log.html state=touch mode=0755 owner=www-data group=www-data
- file: path=/etc/evqueue/conf state=directory mode=0755

- template: src=databases.php.j2
    dest=/etc/evqueue/conf/databases.php
    backup=yes
    owner=0 group=0 mode=0644
- template: src=logger.php.j2
    dest=/etc/evqueue/conf/logger.php
    backup=yes
    owner=0 group=0 mode=0644
- template: src=queueing.php.j2
    dest=/etc/evqueue/conf/queueing.php
    backup=yes
    owner=0 group=0 mode=0644
- template: src=sites_base.php.j2
    dest=/etc/evqueue/conf/sites_base.php
    backup=yes
    owner=0 group=0 mode=0644

- name: evqueue vhost configuration file update
  template: src=evqueue-frontend.conf.j2
    dest=/etc/apache2/sites-available/000-default.conf
    backup=yes
    owner=0 group=0 mode=0644
  notify:
  - restart apache
- lineinfile: dest=/etc/php5/fpm/pool.d/www.conf create=yes state=present line='php_value[include_path] = ".:/etc/evqueue:/var/www/html/evqueue/includes"'
  notify:
  - restart php-fpm
